version: "3.9"
networks:
  core-dev:
    driver: bridge
services:
  app:
   container_name: CoreVS
   build:
     context: .
     dockerfile: Core/Dockerfile
   ports:
     - "80:80"
   networks:
     - core-dev
   depends_on:
     - postgres_db
  postgres_db:
    container_name: CoreDB
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: core-dev
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5440:5432"
    networks:
      - core-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: PgAdmin
    image: dpage/pgadmin4:7.2
    depends_on:
      - postgres_db
    environment:
      PGADMIN_DEFAULT_EMAIL: "www.vol@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - core-dev
volumes:
  postgres-data:
